<?php

namespace Database\Seeders;

use App\Models\Center;
use App\Models\Contract;
use App\Models\Department;
use App\Models\Employee;
use App\Models\Position;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;

class EmployeesSeeder extends Seeder
{
    public function run(): void
    {
        Carbon::setLocale('id');

        $defaultPhotoPath = 'profile-photos/default-avatar.svg';
        if (!Storage::disk('public')->exists($defaultPhotoPath)) {
            Storage::disk('public')->put($defaultPhotoPath, '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="#9CA3AF"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 3c1.66 0 3 1.34 3 3s-1.34 3-3 3-3-1.34-3-3 1.34-3 3-3zm0 14.2c-2.5 0-4.71-1.28-6-3.22.03-1.99 4-3.08 6-3.08 1.99 0 5.97 1.09 6 3.08-1.29 1.94-3.5 3.22-6 3.22z"/></svg>');
        }

        $contracts = Contract::pluck('id', 'name');
        $positions = Position::pluck('id', 'name');
        $centers = Center::pluck('id', 'name');
        $departments = Department::pluck('id', 'name');

        $profiles = [
            [
                'first_name' => 'Darmayansyah',
                'last_name' => 'Direktur',
                'father_name' => 'Surya',
                'mother_name' => 'Kartini',
                'gender' => 1,
                'birth_place' => 'Jakarta',
                'birth_date' => '1975-03-15',
                'national_number' => '3175012503750001',
                'mobile_number' => '08123456001',
                'email' => 'darmayansyah@sanhrms.com',
                'address' => 'Jl. Jenderal Sudirman No. 123, Jakarta Selatan',
                'postal_code' => '12190',
                'degree' => 'S2 Manajemen Strategis',
                'level' => 'C-Level',
                'position' => 'Director',
                'division' => 'Information Technology',
                'branch' => 'Head Office Jakarta Pusat',
                'employment_status' => 'Aktif',
                'is_active' => true,
                'join_date' => '2010-01-15',
                'basic_salary' => 75000000,
                'ptkp_status' => 'K/2',
                'max_leave_allowed' => 18,
                'bank_name' => 'BCA',
            ],
            [
                'first_name' => 'Putri',
                'last_name' => 'Indriani',
                'father_name' => 'Agus',
                'mother_name' => 'Dewi',
                'gender' => 0,
                'birth_place' => 'Bandung',
                'birth_date' => '1985-07-22',
                'national_number' => '3273012207850002',
                'mobile_number' => '08123456002',
                'email' => 'putri.indriani@sanhrms.com',
                'address' => 'Jl. Setiabudi No. 45, Bandung',
                'postal_code' => '40135',
                'degree' => 'S2 Akuntansi',
                'level' => 'Director',
                'position' => 'Manager',
                'division' => 'Finance & Accounting',
                'branch' => 'Head Office Jakarta Pusat',
                'employment_status' => 'Aktif',
                'is_active' => true,
                'join_date' => '2015-03-01',
                'basic_salary' => 35000000,
                'ptkp_status' => 'K/1',
                'max_leave_allowed' => 15,
                'bank_name' => 'Mandiri',
            ],
            [
                'first_name' => 'Sheila',
                'last_name' => 'Hartono',
                'father_name' => 'Budi',
                'mother_name' => 'Sari',
                'gender' => 0,
                'birth_place' => 'Surabaya',
                'birth_date' => '1988-11-10',
                'national_number' => '3578011011880003',
                'mobile_number' => '08123456003',
                'email' => 'sheila.hartono@sanhrms.com',
                'address' => 'Jl. Raya Darmo No. 78, Surabaya',
                'postal_code' => '60271',
                'degree' => 'S1 Psikologi',
                'level' => 'Senior Manager',
                'position' => 'Manager',
                'division' => 'Human Resources',
                'branch' => 'Tangerang',
                'employment_status' => 'Aktif',
                'is_active' => true,
                'join_date' => '2016-07-02',
                'basic_salary' => 28000000,
                'ptkp_status' => 'K/0',
                'max_leave_allowed' => 14,
                'bank_name' => 'BNI',
            ],
            [
                'first_name' => 'Wenny',
                'last_name' => 'Asti Pratiwi',
                'father_name' => 'Hendra',
                'mother_name' => 'Maya',
                'gender' => 0,
                'birth_place' => 'Semarang',
                'birth_date' => '1990-04-05',
                'national_number' => '3374010504900004',
                'mobile_number' => '08123456004',
                'email' => 'wenny.asti@sanhrms.com',
                'address' => 'Jl. Gajah Mada No. 99, Semarang',
                'postal_code' => '50134',
                'degree' => 'S1 Marketing',
                'level' => 'Senior',
                'position' => 'Senior Staff',
                'division' => 'Marketing',
                'branch' => 'Bintaro',
                'employment_status' => 'Aktif',
                'is_active' => true,
                'join_date' => '2018-01-10',
                'basic_salary' => 18000000,
                'ptkp_status' => 'TK/0',
                'bank_name' => 'BCA',
            ],
            [
                'first_name' => 'Morita',
                'last_name' => 'Michi',
                'father_name' => 'Takeshi',
                'mother_name' => 'Yuki',
                'gender' => 1,
                'birth_place' => 'Jakarta',
                'birth_date' => '1987-09-18',
                'national_number' => '3175011809870005',
                'mobile_number' => '08123456005',
                'email' => 'morita.michi@sanhrms.com',
                'address' => 'Jl. Kuningan No. 12, Jakarta Selatan',
                'postal_code' => '12950',
                'degree' => 'S1 Teknik Informatika',
                'level' => 'Lead',
                'position' => 'Senior Staff',
                'division' => 'Information Technology',
                'branch' => 'Head Office Jakarta Pusat',
                'employment_status' => 'Aktif',
                'is_active' => true,
                'join_date' => '2017-05-15',
                'basic_salary' => 22000000,
                'ptkp_status' => 'K/1',
                'bank_name' => 'Mandiri',
            ],
            [
                'first_name' => 'Mohammad',
                'last_name' => 'Reza',
                'father_name' => 'Abdul',
                'mother_name' => 'Nisa',
                'gender' => 1,
                'birth_place' => 'Yogyakarta',
                'birth_date' => '1993-02-28',
                'national_number' => '3404012802930006',
                'mobile_number' => '08123456006',
                'email' => 'mohammad.reza@sanhrms.com',
                'address' => 'Jl. Kaliurang No. 56, Yogyakarta',
                'postal_code' => '55271',
                'degree' => 'S1 Teknik Informatika',
                'level' => 'Mid-Level',
                'position' => 'Staff',
                'division' => 'Information Technology',
                'branch' => 'Bintaro',
                'employment_status' => 'Aktif',
                'is_active' => true,
                'join_date' => '2019-08-01',
                'basic_salary' => 12000000,
                'ptkp_status' => 'TK/0',
                'bank_name' => 'BRI',
            ],
            [
                'first_name' => 'Firda',
                'last_name' => 'Amelia',
                'father_name' => 'Rizal',
                'mother_name' => 'Rina',
                'gender' => 0,
                'birth_place' => 'Medan',
                'birth_date' => '1996-06-14',
                'national_number' => '1271011406960007',
                'mobile_number' => '08123456007',
                'email' => 'firda.amelia@sanhrms.com',
                'address' => 'Jl. Asia No. 23, Medan',
                'postal_code' => '20212',
                'degree' => 'S1 Akuntansi',
                'level' => 'Junior',
                'position' => 'Staff',
                'division' => 'Finance & Accounting',
                'branch' => 'Bekasi',
                'employment_status' => 'Aktif',
                'is_active' => true,
                'join_date' => '2022-02-15',
                'basic_salary' => 8000000,
                'ptkp_status' => 'TK/0',
                'bank_name' => 'BCA',
            ],
            [
                'first_name' => 'Andi',
                'last_name' => 'Saputra',
                'father_name' => 'Joko',
                'mother_name' => 'Sri',
                'gender' => 1,
                'birth_place' => 'Makassar',
                'birth_date' => '1995-01-20',
                'national_number' => '7371012001950008',
                'mobile_number' => '08123456008',
                'email' => 'andi.saputra@sanhrms.com',
                'address' => 'Jl. Pettarani No. 45, Makassar',
                'postal_code' => '90222',
                'degree' => 'S1 Manajemen',
                'level' => 'Mid-Level',
                'position' => 'Staff',
                'division' => 'Sales',
                'branch' => 'Surabaya',
                'employment_status' => 'Dinas Luar',
                'status_reason' => 'Kunjungan Klien',
                'is_active' => true,
                'join_date' => '2020-06-01',
                'basic_salary' => 10000000,
                'ptkp_status' => 'K/0',
                'count_holiday_as_working_day' => true,
                'bank_name' => 'Mandiri',
            ],
            [
                'first_name' => 'Siti',
                'last_name' => 'Nurhaliza',
                'father_name' => 'Ahmad',
                'mother_name' => 'Fatimah',
                'gender' => 0,
                'birth_place' => 'Bogor',
                'birth_date' => '1991-12-12',
                'national_number' => '3201011212910009',
                'mobile_number' => '08123456009',
                'email' => 'siti.nurhaliza@sanhrms.com',
                'address' => 'Jl. Pajajaran No. 88, Bogor',
                'postal_code' => '16143',
                'degree' => 'S1 Ilmu Komunikasi',
                'level' => 'Manager',
                'position' => 'Manager',
                'division' => 'Customer Service',
                'branch' => 'Bandung',
                'employment_status' => 'Aktif',
                'is_active' => true,
                'join_date' => '2017-09-01',
                'basic_salary' => 25000000,
                'ptkp_status' => 'K/2',
                'bank_name' => 'BNI',
            ],
            [
                'first_name' => 'Bintang',
                'last_name' => 'Pratama',
                'father_name' => 'Dedi',
                'mother_name' => 'Lina',
                'gender' => 1,
                'birth_place' => 'Depok',
                'birth_date' => '2000-08-08',
                'national_number' => '3276010808000010',
                'mobile_number' => '08123456010',
                'email' => 'bintang.pratama@sanhrms.com',
                'address' => 'Jl. Margonda Raya No. 100, Depok',
                'postal_code' => '16424',
                'degree' => 'S1 Teknik Informatika',
                'level' => 'Intern',
                'position' => 'Intern',
                'division' => 'Information Technology',
                'branch' => 'Bintaro',
                'employment_status' => 'Aktif',
                'is_active' => true,
                'join_date' => '2024-01-15',
                'basic_salary' => 4500000,
                'ptkp_status' => 'TK/0',
                'max_leave_allowed' => 6,
                'employee_tax_status' => 'Pegawai Tidak Tetap',
                'bank_name' => 'BCA',
            ],
            [
                'first_name' => 'Raka',
                'last_name' => 'Aditya',
                'father_name' => 'Slamet',
                'mother_name' => 'Rahayu',
                'gender' => 1,
                'birth_place' => 'Solo',
                'birth_date' => '1998-05-19',
                'national_number' => '3372011905980011',
                'mobile_number' => '08123456011',
                'email' => 'raka.aditya@sanhrms.com',
                'address' => 'Jl. Slamet Riyadi No. 18, Surakarta',
                'postal_code' => '57141',
                'degree' => 'S1 Sistem Informasi',
                'level' => 'Junior',
                'position' => 'Staff',
                'division' => 'Research & Development',
                'branch' => 'Yogyakarta',
                'employment_status' => 'Masa Percobaan',
                'status_reason' => 'Evaluasi Awal',
                'is_active' => true,
                'join_date' => '2026-02-03',
                'basic_salary' => 7800000,
                'ptkp_status' => 'TK/0',
                'employee_tax_status' => 'Pegawai Tidak Tetap',
                'bank_name' => 'CIMB Niaga',
            ],
            [
                'first_name' => 'Nabila',
                'last_name' => 'Maharani',
                'father_name' => 'Fahmi',
                'mother_name' => 'Ratna',
                'gender' => 0,
                'birth_place' => 'Malang',
                'birth_date' => '1997-04-11',
                'national_number' => '3573011104970012',
                'mobile_number' => '08123456012',
                'email' => 'nabila.maharani@sanhrms.com',
                'address' => 'Jl. Ijen No. 27, Malang',
                'postal_code' => '65119',
                'degree' => 'S1 Psikologi',
                'level' => 'Mid-Level',
                'position' => 'Staff',
                'division' => 'Human Resources',
                'branch' => 'Depok',
                'employment_status' => 'Cuti',
                'status_reason' => 'Cuti Tahunan',
                'is_active' => true,
                'join_date' => '2021-11-08',
                'basic_salary' => 9800000,
                'ptkp_status' => 'K/1',
                'bank_name' => 'Danamon',
            ],
            [
                'first_name' => 'Yusuf',
                'last_name' => 'Mahendra',
                'father_name' => 'Anwar',
                'mother_name' => 'Sulastri',
                'gender' => 1,
                'birth_place' => 'Padang',
                'birth_date' => '1992-09-09',
                'national_number' => '1371010909920013',
                'mobile_number' => '08123456013',
                'email' => 'yusuf.mahendra@sanhrms.com',
                'address' => 'Jl. Khatib Sulaiman No. 8, Padang',
                'postal_code' => '25173',
                'degree' => 'S1 Hukum',
                'level' => 'Senior',
                'position' => 'Senior Staff',
                'division' => 'Legal & Compliance',
                'branch' => 'Head Office Jakarta Pusat',
                'employment_status' => 'Izin',
                'status_reason' => 'Sakit',
                'is_active' => true,
                'join_date' => '2020-02-17',
                'basic_salary' => 16000000,
                'ptkp_status' => 'K/1',
                'bank_name' => 'Permata',
            ],
            [
                'first_name' => 'Kevin',
                'last_name' => 'Sanjaya',
                'father_name' => 'Rudi',
                'mother_name' => 'Elisa',
                'gender' => 1,
                'birth_place' => 'Tangerang',
                'birth_date' => '1999-10-01',
                'national_number' => '3671010110990014',
                'mobile_number' => '08123456014',
                'email' => 'kevin.sanjaya@sanhrms.com',
                'address' => 'Jl. BSD Raya Barat No. 22, Tangerang',
                'postal_code' => '15345',
                'degree' => 'S1 Desain Komunikasi Visual',
                'level' => 'Junior',
                'position' => 'Staff',
                'division' => 'Marketing',
                'branch' => 'Tangerang',
                'employment_status' => 'Izin',
                'status_reason' => 'Acara Keluarga',
                'is_active' => true,
                'join_date' => '2023-06-12',
                'basic_salary' => 7300000,
                'ptkp_status' => 'TK/0',
                'bank_name' => 'BCA',
            ],
            [
                'first_name' => 'Citra',
                'last_name' => 'Lestari',
                'father_name' => 'Imam',
                'mother_name' => 'Murni',
                'gender' => 0,
                'birth_place' => 'Bogor',
                'birth_date' => '1994-03-23',
                'national_number' => '3201012303940015',
                'mobile_number' => '08123456015',
                'email' => 'citra.lestari@sanhrms.com',
                'address' => 'Jl. Pajajaran No. 51, Bogor',
                'postal_code' => '16127',
                'degree' => 'S1 Akuntansi',
                'level' => 'Mid-Level',
                'position' => 'Staff',
                'division' => 'Finance & Accounting',
                'branch' => 'Bogor',
                'employment_status' => 'Terminated',
                'is_active' => false,
                'join_date' => '2021-01-04',
                'basic_salary' => 8900000,
                'ptkp_status' => 'TK/1',
                'bank_name' => 'BNI',
            ],
            [
                'first_name' => 'Deni',
                'last_name' => 'Kurniawan',
                'father_name' => 'Suharto',
                'mother_name' => 'Aminah',
                'gender' => 1,
                'birth_place' => 'Bekasi',
                'birth_date' => '1990-07-30',
                'national_number' => '3275013007900016',
                'mobile_number' => '08123456016',
                'email' => 'deni.kurniawan@sanhrms.com',
                'address' => 'Jl. Ahmad Yani No. 77, Bekasi',
                'postal_code' => '17144',
                'degree' => 'D3 Teknik Elektro',
                'level' => 'Senior',
                'position' => 'Senior Staff',
                'division' => 'Operations',
                'branch' => 'Bekasi',
                'employment_status' => 'Terminated',
                'is_active' => false,
                'join_date' => '2018-04-09',
                'basic_salary' => 14500000,
                'ptkp_status' => 'K/2',
                'count_holiday_as_working_day' => true,
                'bank_name' => 'BRI',
            ],
            [
                'first_name' => 'Rina',
                'last_name' => 'Oktaviani',
                'father_name' => 'Widodo',
                'mother_name' => 'Sri Yanti',
                'gender' => 0,
                'birth_place' => 'Semarang',
                'birth_date' => '1998-12-03',
                'national_number' => '3374010312980017',
                'mobile_number' => '08123456017',
                'email' => 'rina.oktaviani@sanhrms.com',
                'address' => 'Jl. Pandanaran No. 16, Semarang',
                'postal_code' => '50241',
                'degree' => 'S1 Administrasi Bisnis',
                'level' => 'Junior',
                'position' => 'Staff',
                'division' => 'Procurement',
                'branch' => 'Semarang',
                'employment_status' => 'Aktif',
                'is_active' => true,
                'join_date' => '2025-04-21',
                'basic_salary' => 7600000,
                'ptkp_status' => 'TK/0',
                'bank_name' => 'Mandiri',
            ],
            [
                'first_name' => 'Galih',
                'last_name' => 'Ramadhan',
                'father_name' => 'Ridwan',
                'mother_name' => 'Yuni',
                'gender' => 1,
                'birth_place' => 'Depok',
                'birth_date' => '1996-01-27',
                'national_number' => '3276012701960018',
                'mobile_number' => '08123456018',
                'email' => 'galih.ramadhan@sanhrms.com',
                'address' => 'Jl. Juanda No. 30, Depok',
                'postal_code' => '16412',
                'degree' => 'S1 Teknik Industri',
                'level' => 'Mid-Level',
                'position' => 'Staff',
                'division' => 'Operations',
                'branch' => 'Depok',
                'employment_status' => 'Aktif',
                'is_active' => true,
                'join_date' => '2022-08-29',
                'basic_salary' => 10800000,
                'ptkp_status' => 'K/1',
                'count_holiday_as_working_day' => true,
                'bank_name' => 'BCA',
            ],
            [
                'first_name' => 'Valencia',
                'last_name' => 'Putri',
                'father_name' => 'Hartono',
                'mother_name' => 'Diana',
                'gender' => 0,
                'birth_place' => 'Jakarta',
                'birth_date' => '1995-11-06',
                'national_number' => '3175010611950019',
                'mobile_number' => '08123456019',
                'email' => 'valencia.putri@sanhrms.com',
                'address' => 'Jl. Kemang Raya No. 8, Jakarta Selatan',
                'postal_code' => '12730',
                'degree' => 'S1 Hubungan Internasional',
                'level' => 'Senior',
                'position' => 'Senior Staff',
                'division' => 'Customer Service',
                'branch' => 'Head Office Jakarta Pusat',
                'employment_status' => 'Aktif',
                'is_active' => true,
                'join_date' => '2020-10-13',
                'basic_salary' => 15500000,
                'ptkp_status' => 'TK/1',
                'bank_name' => 'CIMB Niaga',
            ],
            [
                'first_name' => 'Alif',
                'last_name' => 'Nugraha',
                'father_name' => 'Dadang',
                'mother_name' => 'Nani',
                'gender' => 1,
                'birth_place' => 'Bandung',
                'birth_date' => '1997-02-14',
                'national_number' => '3273011402970020',
                'mobile_number' => '08123456020',
                'email' => 'alif.nugraha@sanhrms.com',
                'address' => 'Jl. Buah Batu No. 41, Bandung',
                'postal_code' => '40265',
                'degree' => 'S1 Teknik Informatika',
                'level' => 'Mid-Level',
                'position' => 'Staff',
                'division' => 'Research & Development',
                'branch' => 'Bandung',
                'employment_status' => 'Aktif',
                'is_active' => true,
                'join_date' => '2024-11-04',
                'basic_salary' => 11200000,
                'ptkp_status' => 'TK/0',
                'bank_name' => 'BCA',
            ],
            [
                'first_name' => 'Monica',
                'last_name' => 'Chandra',
                'father_name' => 'Gunawan',
                'mother_name' => 'Melati',
                'gender' => 0,
                'birth_place' => 'Medan',
                'birth_date' => '1993-08-25',
                'national_number' => '1271012508930021',
                'mobile_number' => '08123456021',
                'email' => 'monica.chandra@sanhrms.com',
                'address' => 'Jl. Gatot Subroto No. 19, Medan',
                'postal_code' => '20114',
                'degree' => 'S1 Akuntansi',
                'level' => 'Mid-Level',
                'position' => 'Staff',
                'division' => 'Finance & Accounting',
                'branch' => 'Medan',
                'employment_status' => 'Aktif',
                'is_active' => true,
                'join_date' => '2023-03-10',
                'basic_salary' => 11400000,
                'ptkp_status' => 'K/0',
                'bank_name' => 'Mandiri',
            ],
            [
                'first_name' => 'Fikri',
                'last_name' => 'Hidayat',
                'father_name' => 'Maman',
                'mother_name' => 'Nuraini',
                'gender' => 1,
                'birth_place' => 'Cirebon',
                'birth_date' => '1994-06-18',
                'national_number' => '3274011806940022',
                'mobile_number' => '08123456022',
                'email' => 'fikri.hidayat@sanhrms.com',
                'address' => 'Jl. Siliwangi No. 11, Cirebon',
                'postal_code' => '45123',
                'degree' => 'S1 Manajemen',
                'level' => 'Senior',
                'position' => 'Senior Staff',
                'division' => 'Sales',
                'branch' => 'Bandung',
                'employment_status' => 'Dinas Luar',
                'status_reason' => 'Perjalanan Dinas',
                'is_active' => true,
                'join_date' => '2021-04-07',
                'basic_salary' => 14900000,
                'ptkp_status' => 'K/2',
                'count_holiday_as_working_day' => true,
                'bank_name' => 'BNI',
            ],
            [
                'first_name' => 'Nadine',
                'last_name' => 'Saputri',
                'father_name' => 'Hari',
                'mother_name' => 'Sukma',
                'gender' => 0,
                'birth_place' => 'Surabaya',
                'birth_date' => '1999-03-05',
                'national_number' => '3578010503990023',
                'mobile_number' => '08123456023',
                'email' => 'nadine.saputri@sanhrms.com',
                'address' => 'Jl. Ahmad Yani No. 90, Surabaya',
                'postal_code' => '60235',
                'degree' => 'S1 Ilmu Komunikasi',
                'level' => 'Junior',
                'position' => 'Staff',
                'division' => 'Customer Service',
                'branch' => 'Surabaya',
                'employment_status' => 'Aktif',
                'is_active' => true,
                'join_date' => '2026-03-02',
                'basic_salary' => 7200000,
                'ptkp_status' => 'TK/0',
                'bank_name' => 'BCA',
            ],
            [
                'first_name' => 'Bagas',
                'last_name' => 'Wicaksono',
                'father_name' => 'Darto',
                'mother_name' => 'Wati',
                'gender' => 1,
                'birth_place' => 'Bekasi',
                'birth_date' => '2001-01-16',
                'national_number' => '3275011601010024',
                'mobile_number' => '08123456024',
                'email' => 'bagas.wicaksono@sanhrms.com',
                'address' => 'Jl. Patriot No. 33, Bekasi',
                'postal_code' => '17113',
                'degree' => 'D3 Logistik',
                'level' => 'Junior',
                'position' => 'Staff',
                'division' => 'Procurement',
                'branch' => 'Bekasi',
                'employment_status' => 'Masa Percobaan',
                'status_reason' => 'Masa Orientasi',
                'is_active' => true,
                'join_date' => '2026-01-20',
                'basic_salary' => 6900000,
                'ptkp_status' => 'TK/0',
                'employee_tax_status' => 'Pegawai Tidak Tetap',
                'bank_name' => 'BRI',
            ],
            [
                'first_name' => 'Tania',
                'last_name' => 'Kusuma',
                'father_name' => 'Bambang',
                'mother_name' => 'Lilis',
                'gender' => 0,
                'birth_place' => 'Jakarta',
                'birth_date' => '2002-07-28',
                'national_number' => '3175012807020025',
                'mobile_number' => '08123456025',
                'email' => 'tania.kusuma@sanhrms.com',
                'address' => 'Jl. Tebet Timur No. 14, Jakarta Selatan',
                'postal_code' => '12820',
                'degree' => 'S1 Psikologi',
                'level' => 'Intern',
                'position' => 'Intern',
                'division' => 'Human Resources',
                'branch' => 'Head Office Jakarta Pusat',
                'employment_status' => 'Aktif',
                'is_active' => true,
                'join_date' => '2026-03-05',
                'basic_salary' => 4000000,
                'ptkp_status' => 'TK/0',
                'max_leave_allowed' => 6,
                'employee_tax_status' => 'Pegawai Tidak Tetap',
                'bank_name' => 'Mandiri',
            ],
            [
                'first_name' => 'Reva',
                'last_name' => 'Anjani',
                'father_name' => 'Haris',
                'mother_name' => 'Ningrum',
                'gender' => 0,
                'birth_place' => 'Tangerang',
                'birth_date' => '1998-08-17',
                'national_number' => '3671011708980026',
                'mobile_number' => '08123456026',
                'email' => 'reva.anjani@sanhrms.com',
                'address' => 'Jl. MH Thamrin No. 4, Tangerang',
                'postal_code' => '15117',
                'degree' => 'S1 Administrasi Bisnis',
                'level' => 'Junior',
                'position' => 'Staff',
                'division' => 'Operations',
                'branch' => 'Tangerang',
                'employment_status' => 'Aktif',
                'is_active' => true,
                'join_date' => '2025-07-14',
                'basic_salary' => 7700000,
                'ptkp_status' => 'TK/1',
                'count_holiday_as_working_day' => true,
                'bank_name' => 'BCA',
            ],
            [
                'first_name' => 'Dio',
                'last_name' => 'Prasetyo',
                'father_name' => 'Wawan',
                'mother_name' => 'Siti Aisyah',
                'gender' => 1,
                'birth_place' => 'Semarang',
                'birth_date' => '1997-10-21',
                'national_number' => '3374012110970027',
                'mobile_number' => '08123456027',
                'email' => 'dio.prasetyo@sanhrms.com',
                'address' => 'Jl. Pemuda No. 10, Semarang',
                'postal_code' => '50132',
                'degree' => 'S1 Teknik Industri',
                'level' => 'Mid-Level',
                'position' => 'Staff',
                'division' => 'Operations',
                'branch' => 'Semarang',
                'employment_status' => 'Aktif',
                'is_active' => true,
                'join_date' => '2024-06-17',
                'basic_salary' => 9800000,
                'ptkp_status' => 'K/1',
                'count_holiday_as_working_day' => true,
                'bank_name' => 'BNI',
            ],
            [
                'first_name' => 'Melisa',
                'last_name' => 'Christina',
                'father_name' => 'Benny',
                'mother_name' => 'Rosita',
                'gender' => 0,
                'birth_place' => 'Makassar',
                'birth_date' => '1996-12-01',
                'national_number' => '7371010112960028',
                'mobile_number' => '08123456028',
                'email' => 'melisa.christina@sanhrms.com',
                'address' => 'Jl. Boulevard No. 6, Makassar',
                'postal_code' => '90174',
                'degree' => 'S1 Manajemen',
                'level' => 'Mid-Level',
                'position' => 'Staff',
                'division' => 'Sales',
                'branch' => 'Makassar',
                'employment_status' => 'Cuti',
                'status_reason' => 'Cuti Tahunan',
                'is_active' => true,
                'join_date' => '2023-09-18',
                'basic_salary' => 9100000,
                'ptkp_status' => 'TK/0',
                'count_holiday_as_working_day' => true,
                'bank_name' => 'Mandiri',
            ],
        ];

        foreach ($profiles as $index => $profile) {
            $employee = $this->buildEmployee($profile, $index + 1, $defaultPhotoPath, $contracts, $positions, $centers, $departments);

            Employee::updateOrCreate(
                ['national_number' => $employee['national_number']],
                $employee
            );
        }

        $this->command->info('✅ Employees seeded: ' . Employee::count() . ' records');
    }

    private function buildEmployee(array $profile, int $index, string $defaultPhotoPath, $contracts, $positions, $centers, $departments): array
    {
        $joinDate = Carbon::parse($profile['join_date']);
        $birthDate = Carbon::parse($profile['birth_date']);
        $basicSalary = (float) $profile['basic_salary'];
        $maxLeaveAllowed = $profile['max_leave_allowed'] ?? ($profile['position'] === 'Intern' ? 6 : 12);
        $bankName = $profile['bank_name'] ?? 'BCA';

        return [
            'employee_code' => sprintf('000-%03d', $index),
            'barcode' => 'SAN' . str_pad((string) $index, 4, '0', STR_PAD_LEFT),
            'first_name' => $profile['first_name'],
            'last_name' => $profile['last_name'],
            'father_name' => $profile['father_name'],
            'mother_name' => $profile['mother_name'],
            'gender' => $profile['gender'],
            'birth_place' => $profile['birth_place'],
            'birth_date' => $profile['birth_date'],
            'birth_and_place' => $profile['birth_place'] . ', ' . $birthDate->translatedFormat('d F Y'),
            'national_number' => $profile['national_number'],
            'identity_type' => 'KTP',
            'identity_number' => $profile['national_number'],
            'identity_expired_date' => null,
            'is_permanent_identity' => true,
            'mobile_number' => $profile['mobile_number'],
            'email' => $profile['email'],
            'address' => $profile['address'],
            'postal_code' => $profile['postal_code'],
            'degree' => $profile['degree'],
            'notes' => 'Data karyawan contoh untuk kebutuhan demo HRMS PT Sinergi Asta Nusantara.',
            'contract_id' => $contracts[$profile['level']] ?? $contracts->first(),
            'position_id' => $positions[$profile['position']] ?? $positions->first(),
            'department_id' => $departments[$profile['branch']] ?? $departments->first(),
            'center_id' => $centers[$profile['division']] ?? $centers->first(),
            'join_date' => $profile['join_date'],
            'employment_status' => $profile['employment_status'],
            'status_reason' => $profile['status_reason'] ?? null,
            'status_notes' => $profile['status_notes'] ?? null,
            'is_active' => $profile['is_active'],
            'balance_leave_allowed' => $profile['is_active'] ? $maxLeaveAllowed : 0,
            'max_leave_allowed' => $maxLeaveAllowed,
            'delay_counter' => '00:00:00',
            'hourly_counter' => '00:00:00',
            'profile_photo_path' => $defaultPhotoPath,
            'basic_salary' => $basicSalary,
            'ptkp_status' => $profile['ptkp_status'],
            'tax_configuration' => $profile['tax_configuration'] ?? ($basicSalary >= 30000000 ? 'Gross Up' : 'Gross'),
            'prorate_type' => $profile['prorate_type'] ?? 'Based on Working Day',
            'count_holiday_as_working_day' => $profile['count_holiday_as_working_day'] ?? false,
            'salary_type' => 'Monthly',
            'salary_configuration' => $profile['salary_configuration'] ?? 'Taxable',
            'taxable_date' => $joinDate->copy()->addDays(14)->toDateString(),
            'overtime_status' => $profile['overtime_status'] ?? 'Eligible',
            'employee_tax_status' => $profile['employee_tax_status'] ?? ($profile['position'] === 'Intern' || $profile['employment_status'] === 'Masa Percobaan' ? 'Pegawai Tidak Tetap' : 'Pegawai Tetap'),
            'jht_configuration' => 'Default',
            'bpjs_kesehatan_config' => 'By Company',
            'jaminan_pensiun_config' => 'Default',
            'npp_bpjs_ketenagakerjaan' => 'NPP-SAN-2026',
            'bpjs_ketenagakerjaan' => 'BPU' . str_pad((string) $index, 9, '0', STR_PAD_LEFT),
            'bpjs_kesehatan' => 'BPK' . str_pad((string) $index, 9, '0', STR_PAD_LEFT),
            'bpjs_kesehatan_family' => (string) $this->bpjsFamilyCount($profile['ptkp_status']),
            'npwp' => $this->formatNpwp($index),
            'currency' => 'IDR',
            'bpjs_ketenagakerjaan_date' => $joinDate->copy()->addDays(30)->toDateString(),
            'bpjs_kesehatan_date' => $joinDate->copy()->addDays(30)->toDateString(),
            'jaminan_pensiun_date' => $joinDate->copy()->addDays(45)->toDateString(),
            'bank_name' => $bankName,
            'bank_account_number' => $this->generateAccountNumber($index),
            'bank_account_holder' => trim($profile['first_name'] . ' ' . $profile['last_name']),
        ];
    }

    private function bpjsFamilyCount(string $ptkpStatus): int
    {
        return match ($ptkpStatus) {
            'K/3' => 3,
            'K/2' => 2,
            'K/1', 'TK/1' => 1,
            'TK/2' => 2,
            'TK/3' => 3,
            default => 0,
        };
    }

    private function formatNpwp(int $index): string
    {
        return sprintf('12.345.%03d.%d-%03d.000', $index % 1000, $index % 10, ($index * 7) % 1000);
    }

    private function generateAccountNumber(int $index): string
    {
        return '8800' . str_pad((string) ($index * 137), 10, '0', STR_PAD_LEFT);
    }
}
