<?php

namespace Database\Seeders;

use App\Models\Employee;
use App\Models\Contract;
use Illuminate\Database\Seeder;

class EmployeesSeeder extends Seeder
{
    public function run(): void
    {
        $contractId = Contract::first()?->id ?? 1;

        $employees = [
            [
                'employee_code' => '000-001',
                'barcode' => 'AII1',
                'first_name' => 'Darmayansyah',
                'last_name' => 'D',
                'father_name' => 'Surya',
                'mother_name' => 'Kartini',
                'gender' => 1,
                'birth_and_place' => 'Jakarta, 15 Maret 1985',
                'national_number' => '3175012503850001',
                'mobile_number' => '08123456001',
                'email' => 'darmayansyah@company.com',
                'address' => 'Jl. Sudirman No. 123, Jakarta Selatan',
                'degree' => 'S2 Management',
                'contract_id' => $contractId,
                'join_date' => '2018-01-15',
                'is_active' => true,
                'basic_salary' => 25000000,
                'ptkp_status' => 'K/2',
                'max_leave_allowed' => 12,
                'profile_photo_path' => 'profile-photos/.default-photo.jpg',
            ],
            [
                'employee_code' => '000-002',
                'barcode' => 'AII2',
                'first_name' => 'Putri',
                'last_name' => 'Indriani',
                'father_name' => 'Agus',
                'mother_name' => 'Dewi',
                'gender' => 0,
                'birth_and_place' => 'Bandung, 22 Juli 1990',
                'national_number' => '3273012207900002',
                'mobile_number' => '08123456002',
                'email' => 'putri.indriani@company.com',
                'address' => 'Jl. Dago No. 45, Bandung',
                'degree' => 'S1 Akuntansi',
                'contract_id' => $contractId,
                'join_date' => '2019-03-01',
                'is_active' => true,
                'basic_salary' => 12000000,
                'ptkp_status' => 'TK/0',
                'max_leave_allowed' => 12,
                'profile_photo_path' => 'profile-photos/.default-photo.jpg',
            ],
            [
                'employee_code' => '000-003',
                'barcode' => 'AII3',
                'first_name' => 'Sheila',
                'last_name' => 'Hartono',
                'father_name' => 'Budi',
                'mother_name' => 'Sari',
                'gender' => 0,
                'birth_and_place' => 'Surabaya, 10 November 1988',
                'national_number' => '3578011011880003',
                'mobile_number' => '08123456003',
                'email' => 'sheila.hartono@company.com',
                'address' => 'Jl. Pemuda No. 78, Surabaya',
                'degree' => 'S1 Psikologi',
                'contract_id' => $contractId,
                'join_date' => '2018-07-02',
                'is_active' => true,
                'basic_salary' => 6000000,
                'ptkp_status' => 'TK/0',
                'max_leave_allowed' => 12,
                'profile_photo_path' => 'profile-photos/.default-photo.jpg',
            ],
            [
                'employee_code' => '000-004',
                'barcode' => 'AII4',
                'first_name' => 'Wenny',
                'last_name' => 'Asti Pratiwi',
                'father_name' => 'Hendra',
                'mother_name' => 'Maya',
                'gender' => 0,
                'birth_and_place' => 'Semarang, 05 April 1992',
                'national_number' => '3374010504920004',
                'mobile_number' => '08123456004',
                'email' => 'wenny.asti@company.com',
                'address' => 'Jl. Gajah Mada No. 99, Semarang',
                'degree' => 'S1 Marketing',
                'contract_id' => $contractId,
                'join_date' => '2020-01-10',
                'is_active' => true,
                'basic_salary' => 8500000,
                'ptkp_status' => 'K/1',
                'max_leave_allowed' => 12,
                'profile_photo_path' => 'profile-photos/.default-photo.jpg',
            ],
            [
                'employee_code' => '000-005',
                'barcode' => 'AII5',
                'first_name' => 'Morita',
                'last_name' => 'Michi',
                'father_name' => 'Takeshi',
                'mother_name' => 'Yuki',
                'gender' => 1,
                'birth_and_place' => 'Jakarta, 18 September 1987',
                'national_number' => '3175011809870005',
                'mobile_number' => '08123456005',
                'email' => 'morita.michi@company.com',
                'address' => 'Jl. Kuningan No. 12, Jakarta',
                'degree' => 'S1 Teknik Informatika',
                'contract_id' => $contractId,
                'join_date' => '2017-05-15',
                'is_active' => true,
                'basic_salary' => 15000000,
                'ptkp_status' => 'K/0',
                'max_leave_allowed' => 12,
                'profile_photo_path' => 'profile-photos/.default-photo.jpg',
            ],
            [
                'employee_code' => '000-006',
                'barcode' => 'AII6',
                'first_name' => 'Mohammad',
                'last_name' => 'Reza',
                'father_name' => 'Abdul',
                'mother_name' => 'Nisa',
                'gender' => 1,
                'birth_and_place' => 'Yogyakarta, 28 Februari 1991',
                'national_number' => '3404012802910006',
                'mobile_number' => '08123456006',
                'email' => 'mohammad.reza@company.com',
                'address' => 'Jl. Malioboro No. 56, Yogyakarta',
                'degree' => 'S1 Komunikasi',
                'contract_id' => $contractId,
                'join_date' => '2019-08-01',
                'is_active' => true,
                'basic_salary' => 9500000,
                'ptkp_status' => 'TK/0',
                'max_leave_allowed' => 12,
                'profile_photo_path' => 'profile-photos/.default-photo.jpg',
            ],
            [
                'employee_code' => '000-007',
                'barcode' => 'AII7',
                'first_name' => 'Firda',
                'last_name' => 'Amelia',
                'father_name' => 'Rizal',
                'mother_name' => 'Rina',
                'gender' => 0,
                'birth_and_place' => 'Medan, 14 Juni 1993',
                'national_number' => '1271011406930007',
                'mobile_number' => '08123456007',
                'email' => 'firda.amelia@company.com',
                'address' => 'Jl. Asia No. 23, Medan',
                'degree' => 'S1 Akuntansi',
                'contract_id' => $contractId,
                'join_date' => '2021-02-15',
                'is_active' => true,
                'basic_salary' => 7500000,
                'ptkp_status' => 'TK/0',
                'max_leave_allowed' => 12,
                'profile_photo_path' => 'profile-photos/.default-photo.jpg',
            ],
        ];

        foreach ($employees as $emp) {
            Employee::firstOrCreate(
                ['national_number' => $emp['national_number']],
                $emp
            );
        }

        $this->command->info('✅ Employees seeded: ' . Employee::count() . ' records');
    }
}
